version: "2.9"
services:
  node-app:
    build: .
    container_name: nodejs
    restart: always
    ports:
      - 8888:8888
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env